<!--Generated by ::xox::SimpleXmlNodeWriter bthomass at Thu Feb 14 07:25:57 PM EST 2008-->
<xounit:TestResult>
    <name>xoexception Unit Tests</name>
    <nextChildNodeOrder>0</nextChildNodeOrder>
    <nodeOrder>0</nodeOrder>
    <xounit:TestResult>
        <name>::xoexception::test::TestProcTry</name>
        <nextChildNodeOrder>15</nextChildNodeOrder>
        <nodeOrder>0</nodeOrder>
        <xounit:TestPass>
            <name>::xoexception::test::TestProcTry</name>
            <nextChildNodeOrder>0</nextChildNodeOrder>
            <nodeOrder>1</nodeOrder>
            <return>error</return>
            <test>test</test>
            <testedClass>::xoexception::test::TestProcTry</testedClass>
            <testedMethod>test</testedMethod>
        </xounit:TestPass>
        <xounit:TestPass>
            <name>::xoexception::test::TestProcTry</name>
            <nextChildNodeOrder>0</nextChildNodeOrder>
            <nodeOrder>2</nodeOrder>
            <test>testBreak</test>
            <testedClass>::xoexception::test::TestProcTry</testedClass>
            <testedMethod>testBreak</testedMethod>
        </xounit:TestPass>
        <xounit:TestPass>
            <name>::xoexception::test::TestProcTry</name>
            <nextChildNodeOrder>0</nextChildNodeOrder>
            <nodeOrder>3</nodeOrder>
            <test>testCatch</test>
            <testedClass>::xoexception::test::TestProcTry</testedClass>
            <testedMethod>testCatch</testedMethod>
        </xounit:TestPass>
        <xounit:TestPass>
            <name>::xoexception::test::TestProcTry</name>
            <nextChildNodeOrder>0</nextChildNodeOrder>
            <nodeOrder>4</nodeOrder>
            <test>testCatchAssert</test>
            <testedClass>::xoexception::test::TestProcTry</testedClass>
            <testedMethod>testCatchAssert</testedMethod>
        </xounit:TestPass>
        <xounit:TestPass>
            <name>::xoexception::test::TestProcTry</name>
            <nextChildNodeOrder>0</nextChildNodeOrder>
            <nodeOrder>5</nodeOrder>
            <test>testCatchException</test>
            <testedClass>::xoexception::test::TestProcTry</testedClass>
            <testedMethod>testCatchException</testedMethod>
        </xounit:TestPass>
        <xounit:TestPass>
            <name>::xoexception::test::TestProcTry</name>
            <nextChildNodeOrder>0</nextChildNodeOrder>
            <nodeOrder>6</nodeOrder>
            <test>testCatchMultiException</test>
            <testedClass>::xoexception::test::TestProcTry</testedClass>
            <testedMethod>testCatchMultiException</testedMethod>
        </xounit:TestPass>
        <xounit:TestPass>
            <name>::xoexception::test::TestProcTry</name>
            <nextChildNodeOrder>0</nextChildNodeOrder>
            <nodeOrder>7</nodeOrder>
            <test>testCatchReturn</test>
            <testedClass>::xoexception::test::TestProcTry</testedClass>
            <testedMethod>testCatchReturn</testedMethod>
        </xounit:TestPass>
        <xounit:TestPass>
            <name>::xoexception::test::TestProcTry</name>
            <nextChildNodeOrder>0</nextChildNodeOrder>
            <nodeOrder>8</nodeOrder>
            <test>testCatchReturnValue</test>
            <testedClass>::xoexception::test::TestProcTry</testedClass>
            <testedMethod>testCatchReturnValue</testedMethod>
        </xounit:TestPass>
        <xounit:TestPass>
            <name>::xoexception::test::TestProcTry</name>
            <nextChildNodeOrder>0</nextChildNodeOrder>
            <nodeOrder>9</nodeOrder>
            <test>testContinue</test>
            <testedClass>::xoexception::test::TestProcTry</testedClass>
            <testedMethod>testContinue</testedMethod>
        </xounit:TestPass>
        <xounit:TestPass>
            <name>::xoexception::test::TestProcTry</name>
            <nextChildNodeOrder>0</nextChildNodeOrder>
            <nodeOrder>10</nodeOrder>
            <test>testFinally</test>
            <testedClass>::xoexception::test::TestProcTry</testedClass>
            <testedMethod>testFinally</testedMethod>
        </xounit:TestPass>
        <xounit:TestPass>
            <name>::xoexception::test::TestProcTry</name>
            <nextChildNodeOrder>0</nextChildNodeOrder>
            <nodeOrder>11</nodeOrder>
            <test>testNamespace</test>
            <testedClass>::xoexception::test::TestProcTry</testedClass>
            <testedMethod>testNamespace</testedMethod>
        </xounit:TestPass>
        <xounit:TestPass>
            <name>::xoexception::test::TestProcTry</name>
            <nextChildNodeOrder>0</nextChildNodeOrder>
            <nodeOrder>12</nodeOrder>
            <test>testNestedTry</test>
            <testedClass>::xoexception::test::TestProcTry</testedClass>
            <testedMethod>testNestedTry</testedMethod>
        </xounit:TestPass>
        <xounit:TestPass>
            <name>::xoexception::test::TestProcTry</name>
            <nextChildNodeOrder>0</nextChildNodeOrder>
            <nodeOrder>13</nodeOrder>
            <test>testNestedTry2</test>
            <testedClass>::xoexception::test::TestProcTry</testedClass>
            <testedMethod>testNestedTry2</testedMethod>
        </xounit:TestPass>
        <xounit:TestPass>
            <name>::xoexception::test::TestProcTry</name>
            <nextChildNodeOrder>0</nextChildNodeOrder>
            <nodeOrder>14</nodeOrder>
            <test>testRethrowException</test>
            <testedClass>::xoexception::test::TestProcTry</testedClass>
            <testedMethod>testRethrowException</testedMethod>
        </xounit:TestPass>
        <xounit:TestPass>
            <name>::xoexception::test::TestProcTry</name>
            <nextChildNodeOrder>0</nextChildNodeOrder>
            <nodeOrder>15</nodeOrder>
            <test>testReturn</test>
            <testedClass>::xoexception::test::TestProcTry</testedClass>
            <testedMethod>testReturn</testedMethod>
        </xounit:TestPass>
    </xounit:TestResult>
    <xounit:TestResult>
        <name>::xoexception::test::TestThrowable</name>
        <nextChildNodeOrder>1</nextChildNodeOrder>
        <nodeOrder>0</nodeOrder>
        <xounit:TestPass>
            <name>::xoexception::test::TestThrowable</name>
            <nextChildNodeOrder>0</nextChildNodeOrder>
            <nodeOrder>1</nodeOrder>
            <test>test</test>
            <testedClass>::xoexception::test::TestThrowable</testedClass>
            <testedMethod>test</testedMethod>
        </xounit:TestPass>
    </xounit:TestResult>
</xounit:TestResult>

