

namespace eval ::xounit {

    namespace import -force ::xotcl::*

    Class create AssertionError -superclass ::xoexception::Error 

    AssertionError # AssertionError {

        AssertionErrors are thrown when an assert method fails.
        This sends a message to the test runner that the test failed.
        The message from the AssertionError is then used to report
        what failed.  This message is partly generated by the assert method
        and partly specified by the assert message argument.
    }
}

